### ISSUE TITLE
[FEATURE] allow users to close a chat on the home screen

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/Whisper#677]
### Description

A user shouldn't have to open the chat to close it if they want to, this should be a clickable button that doesn't draw attention to itself and is red.

this is the component that needs this change → https://github.com/Dun-sin/Whisper/blob/main/client/src/pages/Start.jsx

### Screenshots

![7jdXrkrFZG](https://github.com/user-attachments/assets/c2fe43ba-2578-4ea2-bdca-ed829e6fe2a6)

**Comment by kartik-raj7** [comment]
Can you assign me this issue

**Comment by Dun-sin** [comment]
> Can you assign me this issue

Sure, thanks for wanting to contribute. Make sure to read the issue description carefully and ask if you have questions. Follow the rules [here](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), or your PR won't be accepted and will be closed. Good luck!

**Comment by kartik-raj7** [comment]
Hey from what I understand from the description is this once the user is connected to someone in chat

![image](https://github.com/user-attachments/assets/c2767e1e-5fd4-462c-8b62-f20485d10b09)

and then moves to some other option say friends for example

![image](https://github.com/user-attachments/assets/11e06fee-ee25-4d11-9f9c-9378e0b559e9)

then when he returns to the chat he should be able to directly access the chat instead of coming onto this screen where there is open chat button

![image](https://github.com/user-attachments/assets/90b27f27-8972-495d-a336-3c9ff05df528)

Is this what we want to implement here?

**Comment by Dun-sin** [comment]
> he user is connected to someone in chat

correct

**Comment by muhammednithal** [comment]
can i work on this issue

**Comment by Priyanshu-2005** [comment]
hey @Dun-sin  I would like to work on this issue Kindly assign it to me.

**Comment by Dun-sin** [comment]
> hey @Dun-sin  I would like to work on this issue Kindly assign it to me.

Sure, thanks for wanting to contribute. Make sure to read the issue description carefully and ask if you have questions. Follow the rules [here](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), or your PR won't be accepted and will be closed. Good luck!

**Comment by bikram993298** [comment]
hey @Dun-sin I would like to work on this issue Kindly assign it to me.

**Comment by Dun-sin** [comment]
@Priyanshu-2005 how's this going?

**Comment by Priyanshu-2005** [comment]
Nearly Done

**Comment by Dun-sin** [comment]
> Nearly Done

Awesome thanks🔥
